<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.payasia.scripts.LoginTest" tests="1" time="125.716" ignored="1" failures="1" timestamp="08 Jul 2021 06:50:31 GMT" skipped="0" hostname="DESKTOP-6D0EAN5" errors="0">
  <testcase name="invalidLoginTest1" time="125.716" classname="com.payasia.scripts.LoginTest">
    <failure type="java.lang.AssertionError" message="Wait limit exceeded : Logout Button -- Element Not Found.">
      <![CDATA[java.lang.AssertionError: Wait limit exceeded : Logout Button -- Element Not Found.
	at org.junit.Assert.fail(Assert.java:88)
	at com.payasia.generic.ListenerReport.logTestFailSnap(ListenerReport.java:222)
	at com.payasia.generic.FunctionsLib.explicitWaitVisibility(FunctionsLib.java:138)
	at com.payasia.pageobjects.LoginPage.verifyValidLoginMsg(LoginPage.java:79)
	at com.payasia.scripts.LoginTest.invalidLoginTest1(LoginTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
    </failure>
  </testcase> <!-- invalidLoginTest1 -->
  <testcase name="validLoginTest" classname="com.payasia.scripts.LoginTest">
    <skipped/>
  </testcase> <!-- validLoginTest -->
</testsuite> <!-- com.payasia.scripts.LoginTest -->
